version: 0.1.{build}

environment:
  matrix:
  - PYTHON: C:\\Python36
  - PYTHON: C:\\Python36-x64

install:
  - "%PYTHON%\\python.exe -m pip install -r test-requirements.txt"
  - "%PYTHON%\\python.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
