name: development-test
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: install testable version
        run: poetry install
      - name: Run unit tests
        run: |
          bandit -r xdrlib2
          bandit -r tests -s B101
          pytest
